
package eu.glowacki.jaxws.client.filetransfer.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFileTransfer", targetNamespace = "http://glowacki.eu/big-data/mtom")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFileTransfer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List&lt;eu.glowacki.jaxws.client.filetransfer.proxy.BigData&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.QueryResponse")
    @Action(input = "http://glowacki.eu/big-data/mtom/IFileTransfer/queryRequest", output = "http://glowacki.eu/big-data/mtom/IFileTransfer/queryResponse")
    public List<BigData> query(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.DownloadResponse")
    @Action(input = "http://glowacki.eu/big-data/mtom/IFileTransfer/downloadRequest", output = "http://glowacki.eu/big-data/mtom/IFileTransfer/downloadResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://glowacki.eu/big-data/mtom/IFileTransfer/download/Fault/IOException")
    })
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://glowacki.eu/big-data/mtom", className = "eu.glowacki.jaxws.client.filetransfer.proxy.UploadResponse")
    @Action(input = "http://glowacki.eu/big-data/mtom/IFileTransfer/uploadRequest", output = "http://glowacki.eu/big-data/mtom/IFileTransfer/uploadResponse")
    public String upload(
        @WebParam(name = "arg0", targetNamespace = "")
        BigData arg0);

}
